---@type LazySpec
return {
  {
    "pwntester/octo.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      "nvim-tree/nvim-web-devicons",
    },
    cmd = { "Octo", "OctoAssigned", "OctoMy" },
    config = function(_, opts)
      require("octo").setup(opts)
      vim.cmd [[command! -nargs=* OctoAssigned Octo pr search assignee:@me is:open archived:false]]
      vim.cmd [[command! -nargs=* OctoMy Octo pr search author:@me is:open archived:false]]
    end,
    opts = {
      use_local_fs = true,
      -- TODO: add prefixes in Which-Key
      mappings = {
        issue = nil,
        pull_request = {
          checkout_pr = { lhs = "<LocalLeader>po" },
          list_commits = { lhs = "<LocalLeader>pc" },
          list_changed_files = { lhs = "<LocalLeader>pf" },
          show_pr_diff = { lhs = "<LocalLeader>pd" },
          add_reviewer = { lhs = "<LocalLeader>va" },
          remove_reviewer = { lhs = "<LocalLeader>vd" },
          close_issue = { lhs = "<LocalLeader>ic" },
          reopen_issue = { lhs = "<LocalLeader>io" },
          list_issues = { lhs = "<LocalLeader>il" },
          reload = { lhs = "<LocalLeader>R" },
          open_in_browser = { lhs = "<LocalLeader>B" },
          copy_url = { lhs = "<LocalLeader>Y" },
          goto_file = { lhs = "<LocalLeader>gf" },
          add_assignee = { lhs = "<LocalLeader>aa" },
          remove_assignee = { lhs = "<LocalLeader>ad" },
          create_label = { lhs = "<LocalLeader>lc" },
          add_label = { lhs = "<LocalLeader>la" },
          remove_label = { lhs = "<LocalLeader>ld" },
          goto_issue = { lhs = "<LocalLeader>gi" },
          add_comment = { lhs = "<LocalLeader>ca" },
          delete_comment = { lhs = "<LocalLeader>cd" },
          merge_pr = nil,
          squash_and_merge_pr = nil,
          rebase_and_merge_pr = nil,
          react_hooray = nil,
          react_heart = nil,
          react_eyes = nil,
          react_thumbs_up = nil,
          react_thumbs_down = nil,
          react_rocket = nil,
          react_laugh = nil,
          react_confused = nil,
        },
        review_thread = {
          goto_issue = { lhs = "<LocalLeader>gi" },
          add_comment = { lhs = "<LocalLeader>ca" },
          add_suggestion = { lhs = "<LocalLeader>sa" },
          delete_comment = { lhs = "<LocalLeader>cd" },
          close_review_tab = nil,
          react_hooray = nil,
          react_heart = nil,
          react_eyes = nil,
          react_thumbs_up = nil,
          react_thumbs_down = nil,
          react_rocket = nil,
          react_laugh = nil,
          react_confused = nil,
        },
        submit_win = {
          approve_review = { lhs = "<LocalLeader><C-a>" },
          comment_review = { lhs = "<LocalLeader><C-m>" },
          request_changes = { lhs = "<LocalLeader><C-r>" },
          close_review_tab = nil,
        },
        review_diff = {
          add_review_comment = { lhs = "<LocalLeader>ca" },
          add_review_suggestion = { lhs = "<LocalLeader>sa" },
          focus_files = { lhs = "<LocalLeader>e" },
          toggle_files = { lhs = "<LocalLeader>b" },
          toggle_viewed = { lhs = "<LocalLeader><LocalLeader>" },
          goto_file = { lhs = "<LocalLeader>gf" },
          close_review_tab = nil,
        },
        file_panel = {
          refresh_files = { lhs = "<LocalLeader>R" },
          focus_files = { lhs = "<LocalLeader>e" },
          toggle_files = { lhs = "<LocalLeader>b" },
          toggle_viewed = { lhs = "<LocalLeader><LocalLeader>" },
          close_review_tab = nil,
        },
      },
    },
  },
}
